package com.cgmuros.pruebazk.model;
// Generated Dec 1, 2015 11:35:41 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Documento generated by hbm2java
 */
public class Documento  implements java.io.Serializable {


     private int idDocumento;
     private String nombreArchivo;
     private byte[] documentoFisico;
     private Date fechaCompra;
     private Integer mesesGarantia;

    public Documento() {
    }

	
    public Documento(int idDocumento) {
        this.idDocumento = idDocumento;
    }
    public Documento(int idDocumento, String nombreArchivo, byte[] documentoFisico, Date fechaCompra, Integer mesesGarantia) {
       this.idDocumento = idDocumento;
       this.nombreArchivo = nombreArchivo;
       this.documentoFisico = documentoFisico;
       this.fechaCompra = fechaCompra;
       this.mesesGarantia = mesesGarantia;
    }
   
    public int getIdDocumento() {
        return this.idDocumento;
    }
    
    public void setIdDocumento(int idDocumento) {
        this.idDocumento = idDocumento;
    }
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }
    public byte[] getDocumentoFisico() {
        return this.documentoFisico;
    }
    
    public void setDocumentoFisico(byte[] documentoFisico) {
        this.documentoFisico = documentoFisico;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public Integer getMesesGarantia() {
        return this.mesesGarantia;
    }
    
    public void setMesesGarantia(Integer mesesGarantia) {
        this.mesesGarantia = mesesGarantia;
    }




}


